### ISSUE TITLE
Parsing/Translating

### ISSUE THREAD

**Issue by bramtayl** [davidagold/StructuredQueries.jl#12]
I really like what I can understand of jplyr. And you might be doing this already, but I can't tell. But I think it would be useful to keep the machinery separated into parts and labelled: parsers, which parse queries into graphs, the infrastructure for the graph objects themselves, and translators, which translate graphs into code. So that people can write new parsers to translate queries from other languages (LINQ, SQL) into graph objects and new translators to translate graphs into languages besides julia, or even different kinds of julia code.

P.S. I find the word graph non-intuitive. Maybe tree? Also, I find the all the "helper" objects/functions non-intuitive. Maybe parsed_transformation or something? If that's what they are...

**Comment by davidagold** [comment]
I'm glad you like the package so far. Do stay tuned -- I hope to have it, or at least some subset of its intended functionality, ready for public use by the end of the summer.

There's no "parse" step, in the sense of transforming a string into an expression tree. And there's no need for one. I don't intend ever to support more than one user-facing API, and the one I've settled on is the dplyr-like API currently in progress. However, users are certainly able to define their own methods that do whatever they wish with a graph depending on the type of its data source:

``` julia
julia> using jplyr

julia> type MyDataSource end

julia> mydata = MyDataSource()
MyDataSource()

julia> function jplyr._collect(::MyDataSource, ::jplyr.FilterNode)
         println("I'm filtering a MyDataSource object")
         return MyDataSource()
       end

julia> function jplyr._collect(::MyDataSource, ::jplyr.SelectNode)
         println("I'm selecting a MyDataSource object")
         return MyDataSource()
       end

julia> qry = @query mydata |>
                  filter(a == b) |> 
                  select(c)
jplyr.SelectNode(jplyr.FilterNode(jplyr.DataNode(MyDataSource()),Expr[:(a == b)],jplyr.Helper{jplyr.FilterNode}(Tuple[(#1,Symbol[:a,:b])])),Union{Expr,Symbol}[:c])

julia> collect(qry)
I'm filtering a MyDataSource object
I'm selecting a MyDataSource object
MyDataSource()
```

The term "graph" refers to a more general trend of representing the flow of data through operations with a graph. A tree is a graph. I think the terminology is fine.

The helpers are not parsed transformations -- they are collections of objects that are necessary in order to operate on an in-memory Julia data source. So, the name "helper" is accurate.

**Comment by bramtayl** [comment]
Hmm. Well it's definitely not worth disagreeing about syntax. What you're calling graph to me does seem a lot like a souped up version of an expression tree, just of an abstract query language that's not julia. And what you're doing seems to me to be taking a macros or a query, translating first to that abstract query language, and then translating it back to vanilla julia.

**Comment by bramtayl** [comment]
See PanQuery.jl for the basic ideas here.
